#! /usr/bin/env python
import sys
import cooperative_transport.controller
if __name__ == '__main__':
    controller_index = int(sys.argv[1])
    cooperative_transport.controller.main(controller_index)
