#! /usr/bin/env python
import sys
import xml.etree.ElementTree as ET

def objects_position(file_name, poses):
    """Edit poses in a world file.
    
    Arguments:
    file_name (str): world file path
    poses (dict): pose of the objects {object_name: pose}
    """

    # Open world file
    tree = ET.parse(file_name)

    root = tree.getroot()
    root_state = root.findall('world')[0].findall('state')[0]

    objects_pose = poses
    models = {} 

    for model in root_state.iter('model'):
        if model.attrib['name'] in objects_pose:
            models[model.attrib['name']] = model

    # Edit pose elements
    for model_name, element in models.iteritems():
        element.findall('pose')[0].text = objects_pose[model_name]
    
    # Write world file
    tree.write(file_name)

if __name__ == '__main__':
    """Call method that is used to edit gazebo world file. """
    args_number = len(sys.argv) - 2

    poses = {}
    poses['my_box'] = sys.argv[2]

    # Edit dictionary in form {... object: 'x y z phi theta psi' ...} 
    for i in range(3, args_number):
        if i == 3:
            poses['iRobot'] = sys.argv[i]
        else:
            poses['iRobot_' + str(i-4)] = sys.argv[i]

    if args_number == 4:
        objects_position(sys.argv[1] + '/worlds/onerobot.world', poses)
    if args_number == 6:
        objects_position(sys.argv[1] + '/worlds/severalrobots.world', poses)
